Copy source code to workspace directory

diff --git a/norkyst b/norkyst
--- a/norkyst
+++ b/norkyst
@@ -1,30 +1,47 @@
 #!/usr/bin/env bash
 
+set -e  # Exit script if any command fails
 
+GIT_SOURCE="$(dirname "$0")"
+SESSION_KEY="$(date --utc +%Y-%m-%d_%H.%M.%S)"
+SESSION_WORKSPACE="$USERWORK/norkyst_runs/$SESSION_KEY"
+LOGFILE="$SESSION_WORKSPACE/norkyst.log"
+mkdir -p "$SESSION_WORKSPACE"
+
+echo ""
 echo "Starting NorKyst, $(date)"
+echo "Current directory: $(pwd)"
+echo "Current commit: $(git rev-parse HEAD)"
+echo "Workspace: $SESSION_WORKSPACE"
 
-
+echo ""
+echo "Load Sigma2 modules"
 module --quiet purge
 module load netcdf4-python/1.5.7-intel-2021b
 module list
 
-
-echo "Activate cached python environment"
+echo ""
+echo "Update cached python environment"
 GIT_SOURCE="$(dirname "$0")"
 CACHE_DIR="$GIT_SOURCE/cache"
-VENV_DIR="$GIT_SOURCE/cache/venv_norkyst"
-python -m venv --upgrade "$VENV_DIR"
-source "$VENV_DIR/bin/activate"
-
-
-echo "Update python packages"
+VENV_SUBDIR="cache/venv_norkyst"
+python -m venv --upgrade "$GIT_SOURCE/$VENV_SUBDIR"
+source "$GIT_SOURCE/$VENV_SUBDIR/bin/activate"
 python -m pip install --upgrade pip
-python -m pip install --editable "$GIT_SOURCE"
+python -m pip install -r "$GIT_SOURCE/requirements.txt"
+deactivate
 
 
-SESSION_KEY="$(date --utc +%Y-%m-%d_%H%M%S)"
-SESSION_WORKSPACE="$USERWORK/norkyst_runs/$SESSION_KEY"
-echo "Create workspace in $SESSION_WORKSPACE"
-echo "Copy from $GIT_SOURCE"
+echo ""
+echo "Copy source code to workspace directory"
+rsync -rltp --exclude=".git" "$GIT_SOURCE" "$SESSION_WORKSPACE"
+source "$SESSION_WORKSPACE/$VENV_SUBDIR/bin/activate"
 
+
+echo ""
+echo "Install norkyst python package"
+python -m pip install --no-deps --editable "$SESSION_WORKSPACE"
+
+
+echo ""
 echo "NorKyst is finished, $(date)"
